---
- hosts: all
  vars:
    created_username: ansible

  tasks:
    - name: Create a new regular
      user:
        name: "{{ created_username }}"
        state: present
        create_home: true

    - name: Set authorized key for ansible user
      authorized_key:
        user: "{{ created_username }}"
        state: present
        key: "{{ lookup('file', 'ansible.pub') }}"
        
    - name: Setup passwordless sudo for ansible user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
        #	when: ansible_host non e' proxmox
