---
- hosts: all
  gather_facts: true
  tasks:
    - name: Set authorized key took from url
      authorized_key:
        user: ansible
        state: present
        key: https://github.com/ansible.keys

