---
- hosts: all
  gather_facts: true
  vars:
    created_username: ansible
  tasks:
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ created_username }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        
    - name: Set authorized key took from url
      authorized_key:
        user: ansible
        state: present
        key: ansible.keys

